name: test
on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: "yarn"
      - run: "yarn lint && yarn typecheck"
      - run: "yarn test"
